name = "CropPhenoFromDrones"
uuid = "1980905c-5a30-4ba1-8d5b-a530af7a581f"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
